AspNetCoreAuthCookie/Controllers/AccessesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreAuthCookie.Controllers
{

    //Controller para testar o acesso de cada tipo de usúario
    [Authorize]
    public class AccessesController : Controller
    {
        [Authorize(Roles = "Admin")]  // somente usuarios admin podem acessar
        public IActionResult Admin()
        {
            return View();
        }

        [Authorize(Roles = "Admin, Manager")] //somente usuarios admin e manager podem acessar
        public IActionResult Manager()
        {
            return View();
        }

        [Authorize(Roles = "Admin, Users")] // somente usuarios admim e users podem acessar
        public IActionResult Users()
        {
            return View();
        }

        [Authorize(Policy = "Gestores")]
        public IActionResult Policy()
        {
            return View();
        }
    }
}

AspNetCoreAuthCookie/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCoreAuthCookie</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AspNetCoreAuthCookie</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                    @if ((await AuthorizationService.AuthorizeAsync(User, "Gestores")).Succeeded)
                    {
                        <li><a asp-area="" asp-controller="Accesses" asp-action="Policy">Policy</a></li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="Accesses" asp-action="Admin">Admin</a></li>
                    }
                    @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                    {
                        <li><a asp-area="" asp-controller="Accesses" asp-action="Manager">Manager</a></li>
                    }
                    @if (User.IsInRole("Admin") || User.IsInRole("Users"))
                    {
                        <li><a asp-area="" asp-controller="Accesses" asp-action="Users">Users</a></li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Users" asp-action="Index">Usuarios</a></li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @*<li>
                                <a>Olá! @User.Identity.Name</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="Account" asp-action="Logout">Sair</a>
                            </li>*@

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello! @User.Identity.Name<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Users" asp-action="ChangePassword">Change Password</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a asp-area="" asp-controller="Users" asp-action="Register">Create an account</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - AspNetCoreAuthCookie</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>